import { createClient } from '@supabase/supabase-js';

// Validate environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('❌ Missing required Supabase environment variables. Please check your .env.local file.');
}

// Validate URL format
if (!supabaseUrl.includes('supabase.co') && !supabaseUrl.includes('localhost:8090')) {
  throw new Error('❌ Invalid Supabase URL format. Please check your environment variables.');
}

// Validate key format
if (supabaseAnonKey.length < 20) {
  throw new Error('❌ Invalid Supabase key format. Please check your environment variables.');
}


// Create Supabase client
export const supabase = createClient(
  supabaseUrl || 'https://placeholder.supabase.co',
  supabaseAnonKey || 'placeholder-key'
);

// User account interface for database (snake_case - matches Supabase)
export interface UserAccount {
  id?: string; // Optional since it's auto-generated by database
  account_id: string;
  username: string;
  email: string;
  hash_key: string;
  password?: string; // Added for authentication
  avatar?: string;
  score: number;
  created_at: string;
  last_active: string;
}

// User account interface for frontend (camelCase)
export interface UserAccountFrontend {
  id?: string; // Optional since it's auto-generated by database
  accountId: string;
  username: string;
  email: string;
  hashKey: string;
  avatar?: string;
  score: number;
  createdAt: string;
  lastActive: string;
}

// Reset token interface for database (snake_case - matches Supabase)
export interface ResetToken {
  id?: string;
  email: string;
  token: string;
  expires_at: string;
  created_at: string;
  used_at?: string;
  user_id?: string;
}

// Reset token interface for frontend (camelCase)
export interface ResetTokenFrontend {
  id?: string;
  email: string;
  token: string;
  expiresAt: string;
  createdAt: string;
  usedAt?: string;
  userId?: string;
}

// Database operations for user accounts
export class UserAccountDB {
  private static instance: UserAccountDB;

  static getInstance(): UserAccountDB {
    if (!UserAccountDB.instance) {
      UserAccountDB.instance = new UserAccountDB();
    }
    return UserAccountDB.instance;
  }

  // Get all users sorted by score (for leaderboard)
  async getAllUsers(): Promise<UserAccount[]> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('id, account_id, username, email, avatar, score, last_active, created_at, hash_key')
        .order('last_active', { ascending: false }) // Sort by last_active instead of score
        .limit(100); // Limit to last 100 active users to reduce egress

      if (error) throw error;
      return data || [];
    } catch (error) {
      return [];
    }
  }

  // Get user by account ID
  async getUserByAccountId(accountId: string): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('id, account_id, username, email, avatar, score, last_active, created_at, hash_key')
        .eq('account_id', accountId)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Get user by email
  async getUserByEmail(email: string): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('*')
        .eq('email', email)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Update existing user by account_id
  async updateUserByAccountId(accountId: string, userData: Partial<UserAccount>): Promise<UserAccount | null> {
    try {
      // Remove id field to let PostgreSQL keep the existing UUID
      const { id, ...userDataWithoutId } = userData;
      
      const { data, error } = await supabase
        .from('users')
        .update(userDataWithoutId)
        .eq('account_id', accountId)
        .select()
        .single();

      if (error) {
        throw error;
      }
      
      return data;
    } catch (error) {
      return null;
    }
  }

  // Create or update user (upsert)
  async upsertUser(userData: Partial<UserAccount>): Promise<UserAccount | null> {
    try {
      // Remove id field to let PostgreSQL auto-generate UUID
      const { id, ...userDataWithoutId } = userData;
      
      const { data, error } = await supabase
        .from('users')
        .upsert(userDataWithoutId)
        .select()
        .single();

      if (error) {
        throw error;
      }
      
      return data;
    } catch (error) {
      return null;
    }
  }

  // Update user study time and score
  async updateUserScore(accountId: string, score: number): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .update({
          score: score,
          last_active: new Date().toISOString()
        })
        .eq('account_id', accountId)
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Update user profile
  async updateUserProfile(accountId: string, username: string, avatar?: string): Promise<UserAccount | null> {
    try {
      // Build update object dynamically
      const updateData: any = {
        last_active: new Date().toISOString()
      };
      
      if (username) {
        updateData.username = username;
      }
      
      if (avatar !== undefined) {
        updateData.avatar = avatar;
      }
      
      const { data, error } = await supabase
        .from('users')
        .update(updateData)
        .eq('account_id', accountId)
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Subscribe to real-time changes
  subscribeToUsers(callback: (payload: any) => void) {
    try {
      // Subscribe to the users table for real-time updates
      const subscription = supabase
        .channel('users_changes')
        .on('postgres_changes', 
          { event: '*', schema: 'public', table: 'users' },
          async (payload) => {
            // Send only the changed payload, not all users
            callback(payload);
          }
        )
        .subscribe();

      // Initial load - get all users once
      this.getAllUsers().then(users => {
        callback({ eventType: 'INITIAL_LOAD', new: users });
      });
      
      return subscription;
    } catch (error) {
      // Error subscribing to users
    }
  }

  // Unsubscribe from real-time changes
  unsubscribeFromUsers() {
    try {
      supabase.channel('users_changes').unsubscribe();
    } catch (error) {
      // Error unsubscribing from users
    }
  }

  // Initialize Supabase connection
  async initialize(): Promise<boolean> {
    try {
      const { data, error } = await supabase.from('users').select('account_id').limit(1);
      return !error;
    } catch (error) {
      return false;
    }
  }
}

// Database operations for reset tokens
export class ResetTokenDB {
  private static instance: ResetTokenDB;

  static getInstance(): ResetTokenDB {
    if (!ResetTokenDB.instance) {
      ResetTokenDB.instance = new ResetTokenDB();
    }
    return ResetTokenDB.instance;
  }

  // Create a new reset token
  async createResetToken(email: string, token: string, expiresAt: string, userId?: string): Promise<ResetToken | null> {
    try {
      const { data, error } = await supabase
        .from('reset_tokens')
        .insert({
          email,
          token,
          expires_at: expiresAt,
          user_id: userId
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Find reset token by token
  async findTokenByToken(token: string): Promise<ResetToken | null> {
    try {
      const { data, error } = await supabase
        .from('reset_tokens')
        .select('*')
        .eq('token', token)
        .eq('used_at', null) // Only return unused tokens
        .gt('expires_at', new Date().toISOString()) // Only return non-expired tokens
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Find reset token by email
  async findTokenByEmail(email: string): Promise<ResetToken | null> {
    try {
      const { data, error } = await supabase
        .from('reset_tokens')
        .select('*')
        .eq('email', email)
        .eq('used_at', null) // Only return unused tokens
        .gt('expires_at', new Date().toISOString()) // Only return non-expired tokens
        .order('created_at', { ascending: false }) // Get the most recent token
        .limit(1)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Mark token as used
  async markTokenAsUsed(token: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('reset_tokens')
        .update({ used_at: new Date().toISOString() })
        .eq('token', token);

      if (error) throw error;
      return true;
    } catch (error) {
      return false;
    }
  }

  // Clean up expired tokens
  async cleanupExpiredTokens(): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('reset_tokens')
        .delete()
        .lt('expires_at', new Date().toISOString());

      if (error) throw error;
      return true;
    } catch (error) {
      return false;
    }
  }

  // Delete all tokens for an email
  async deleteTokensByEmail(email: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('reset_tokens')
        .delete()
        .eq('email', email);

      if (error) throw error;
      return true;
    } catch (error) {
      return false;
    }
  }
}

// Export singleton instances
export const userDB = UserAccountDB.getInstance();
export const resetTokenDB = ResetTokenDB.getInstance();

// Check if Supabase is available
export const isSupabaseAvailable = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.from('users').select('account_id').limit(1);
    
    if (error) {
      return false;
    }
    
    return true;
  } catch (error) {
    return false;
  }
};
