import { createClient } from '@supabase/supabase-js';

// Validate environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('❌ Missing required Supabase environment variables. Please check your .env.local file.');
}

// Validate URL format
if (!supabaseUrl.includes('supabase.co') && !supabaseUrl.includes('localhost:8090')) {
  throw new Error('❌ Invalid Supabase URL format. Please check your environment variables.');
}

// Validate key format
if (supabaseAnonKey.length < 20) {
  throw new Error('❌ Invalid Supabase key format. Please check your environment variables.');
}


// Create Supabase client
export const supabase = createClient(
  supabaseUrl || 'https://placeholder.supabase.co',
  supabaseAnonKey || 'placeholder-key'
);

// User account interface for database (snake_case - matches Supabase)
export interface UserAccount {
  id?: string; // Optional since it's auto-generated by database
  account_id: string;
  username: string;
  email: string;
  hash_key: string;
  password?: string; // Added for authentication
  avatar?: string;
  score: number;
  referral_code?: string;
  country?: string; // User's country
  browser_id?: string; // Unique browser identifier
  device_id?: string; // Unique device identifier
  subscription_plan?: 'free' | 'monthly' | 'yearly'; // Subscription plan
  subscription_start_date?: string; // Subscription start date
  subscription_end_date?: string; // Subscription end date
  auto_renew?: boolean; // Auto-renew subscription
  created_at: string;
  last_active: string;
}

// User account interface for frontend (camelCase)
export interface UserAccountFrontend {
  id?: string; // Optional since it's auto-generated by database
  accountId: string;
  username: string;
  email: string;
  hashKey: string;
  avatar?: string;
  score: number;
  referralCode?: string;
  country?: string; // User's country
  browserId?: string; // Unique browser identifier
  deviceId?: string; // Unique device identifier
  subscriptionPlan?: 'free' | 'monthly' | 'yearly'; // Subscription plan
  subscriptionStartDate?: string; // Subscription start date
  subscriptionEndDate?: string; // Subscription end date
  autoRenew?: boolean; // Auto-renew subscription
  createdAt: string;
  lastActive: string;
}

// Reset token interface for database (snake_case - matches Supabase)
export interface ResetToken {
  id?: string;
  email: string;
  token: string;
  expires_at: string;
  created_at: string;
  used_at?: string;
  user_id?: string;
}

// Reset token interface for frontend (camelCase)
export interface ResetTokenFrontend {
  id?: string;
  email: string;
  token: string;
  expiresAt: string;
  createdAt: string;
  usedAt?: string;
  userId?: string;
}

// Challenge interface for database (snake_case - matches Supabase)
export interface Challenge {
  id?: string;
  challenger_id: string;
  opponent_id: string;
  status: 'pending' | 'active' | 'completed' | 'cancelled';
  winner_id?: string;
  started_at?: string;
  ended_at?: string;
  duration_seconds: number;
  created_at: string;
  updated_at: string;
}

// Challenge interface for frontend (camelCase)
export interface ChallengeFrontend {
  id?: string;
  challengerId: string;
  opponentId: string;
  status: 'pending' | 'active' | 'completed' | 'cancelled';
  winnerId?: string;
  startedAt?: string;
  endedAt?: string;
  durationSeconds: number;
  createdAt: string;
  updatedAt: string;
}

// Challenge session interface for database (snake_case - matches Supabase)
export interface ChallengeSession {
  id?: string;
  challenge_id: string;
  user_id: string;
  study_time_seconds: number;
  is_studying: boolean;
  session_start_time: string;
  last_update_time: string;
  created_at: string;
  updated_at: string;
}

// Challenge session interface for frontend (camelCase)
export interface ChallengeSessionFrontend {
  id?: string;
  challengeId: string;
  userId: string;
  studyTimeSeconds: number;
  isStudying: boolean;
  sessionStartTime: string;
  lastUpdateTime: string;
  createdAt: string;
  updatedAt: string;
}

// Waiting list interface for database (snake_case - matches Supabase)
export interface WaitingListEntry {
  id?: string;
  user_id: string;
  joined_at: string;
  expires_at: string;
  status: 'waiting' | 'matched' | 'expired';
  created_at: string;
}

// Waiting list interface for frontend (camelCase)
export interface WaitingListEntryFrontend {
  id?: string;
  userId: string;
  joinedAt: string;
  expiresAt: string;
  status: 'waiting' | 'matched' | 'expired';
  createdAt: string;
}

// Referral interface for database (snake_case - matches Supabase)
export interface Referral {
  id?: string;
  referrer_id: string;
  referred_user_id: string;
  referral_code: string;
  points_rewarded: number;
  created_at: string;
}

// Referral interface for frontend (camelCase)
export interface ReferralFrontend {
  id?: string;
  referrerId: string;
  referredUserId: string;
  referralCode: string;
  pointsRewarded: number;
  createdAt: string;
}

// Study room interface for database (snake_case - matches Supabase)
export interface StudyRoom {
  id?: string;
  name: string;
  creator_id: string;
  created_at: string;
}

// Study room interface for frontend (camelCase)
export interface StudyRoomFrontend {
  id?: string;
  name: string;
  creatorId: string;
  createdAt: string;
}

// Room member interface for database (snake_case - matches Supabase)
export interface RoomMember {
  id?: string;
  room_id: string;
  user_id: string;
  joined_at: string;
  left_at?: string;
  last_heartbeat: string;
}

// Room member interface for frontend (camelCase)
export interface RoomMemberFrontend {
  id?: string;
  roomId: string;
  userId: string;
  joinedAt: string;
  leftAt?: string;
  lastHeartbeat: string;
}

// Database operations for user accounts
export class UserAccountDB {
  private static instance: UserAccountDB;

  static getInstance(): UserAccountDB {
    if (!UserAccountDB.instance) {
      UserAccountDB.instance = new UserAccountDB();
    }
    return UserAccountDB.instance;
  }

  // Get all users sorted by score (for leaderboard)
  async getAllUsers(): Promise<UserAccount[]> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('id, account_id, username, email, avatar, score, last_active, created_at, hash_key, country, browser_id, device_id')
        .order('last_active', { ascending: false }) // Sort by last_active instead of score

      if (error) throw error;
      return data || [];
    } catch (error) {
      return [];
    }
  }

  // Get user by account ID
  async getUserByAccountId(accountId: string): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('id, account_id, username, email, avatar, score, last_active, created_at, hash_key, country, browser_id, device_id')
        .eq('account_id', accountId)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Get user by ID
  async getUserById(id: string): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('id, account_id, username, email, avatar, score, last_active, created_at, hash_key, country, browser_id, device_id')
        .eq('id', id)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Get user by email
  async getUserByEmail(email: string): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('*')
        .eq('email', email)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Update existing user by account_id
  async updateUserByAccountId(accountId: string, userData: Partial<UserAccount>): Promise<UserAccount | null> {
    try {
      // Remove id field to let PostgreSQL keep the existing UUID
      const { id, ...userDataWithoutId } = userData;
      
      const { data, error } = await supabase
        .from('users')
        .update(userDataWithoutId)
        .eq('account_id', accountId)
        .select()
        .single();

      if (error) {
        throw error;
      }
      
      return data;
    } catch (error) {
      return null;
    }
  }

  // Create or update user (upsert)
  async upsertUser(userData: Partial<UserAccount>): Promise<UserAccount | null> {
    try {
      // Remove id field to let PostgreSQL auto-generate UUID
      const { id, ...userDataWithoutId } = userData;
      
      const { data, error } = await supabase
        .from('users')
        .upsert(userDataWithoutId)
        .select()
        .single();

      if (error) {
        throw error;
      }
      
      return data;
    } catch (error) {
      return null;
    }
  }

  // Update user profile
  async updateUserProfile(accountId: string, username: string, avatar?: string): Promise<UserAccount | null> {
    try {
      // Build update object dynamically
      const updateData: any = {
        last_active: new Date().toISOString()
      };
      
      if (username) {
        updateData.username = username;
      }
      
      if (avatar !== undefined) {
        updateData.avatar = avatar;
      }
      
      const { data, error } = await supabase
        .from('users')
        .update(updateData)
        .eq('account_id', accountId)
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Subscribe to real-time changes
  subscribeToUsers(callback: (payload: any) => void) {
    try {
      // Subscribe to the users table for real-time updates
      const subscription = supabase
        .channel('users_changes')
        .on('postgres_changes', 
          { event: '*', schema: 'public', table: 'users' },
          async (payload) => {
            // Send only the changed payload, not all users
            callback(payload);
          }
        )
        .subscribe();

      // Initial load - get all users once
      this.getAllUsers().then(users => {
        callback({ eventType: 'INITIAL_LOAD', new: users });
      });
      
      return subscription;
    } catch (error) {
      // Error subscribing to users
    }
  }

  // Unsubscribe from real-time changes
  unsubscribeFromUsers() {
    try {
      supabase.channel('users_changes').unsubscribe();
    } catch (error) {
      // Error unsubscribing from users
    }
  }

  // Initialize Supabase connection
  async initialize(): Promise<boolean> {
    try {
      const { data, error } = await supabase.from('users').select('account_id').limit(1);
      return !error;
    } catch (error) {
      return false;
    }
  }
}

// Database operations for reset tokens
export class ResetTokenDB {
  private static instance: ResetTokenDB;

  static getInstance(): ResetTokenDB {
    if (!ResetTokenDB.instance) {
      ResetTokenDB.instance = new ResetTokenDB();
    }
    return ResetTokenDB.instance;
  }

  // Create a new reset token
  async createResetToken(email: string, token: string, expiresAt: string, userId?: string): Promise<ResetToken | null> {
    try {
      const { data, error } = await supabase
        .from('reset_tokens')
        .insert({
          email,
          token,
          expires_at: expiresAt,
          user_id: userId
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Find reset token by token
  async findTokenByToken(token: string): Promise<ResetToken | null> {
    try {
      const { data, error } = await supabase
        .from('reset_tokens')
        .select('*')
        .eq('token', token)
        .eq('used_at', null) // Only return unused tokens
        .gt('expires_at', new Date().toISOString()) // Only return non-expired tokens
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Find reset token by email
  async findTokenByEmail(email: string): Promise<ResetToken | null> {
    try {
      const { data, error } = await supabase
        .from('reset_tokens')
        .select('*')
        .eq('email', email)
        .eq('used_at', null) // Only return unused tokens
        .gt('expires_at', new Date().toISOString()) // Only return non-expired tokens
        .order('created_at', { ascending: false }) // Get the most recent token
        .limit(1)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Mark token as used
  async markTokenAsUsed(token: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('reset_tokens')
        .update({ used_at: new Date().toISOString() })
        .eq('token', token);

      if (error) throw error;
      return true;
    } catch (error) {
      return false;
    }
  }

  // Clean up expired tokens
  async cleanupExpiredTokens(): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('reset_tokens')
        .delete()
        .lt('expires_at', new Date().toISOString());

      if (error) throw error;
      return true;
    } catch (error) {
      return false;
    }
  }

  // Delete all tokens for an email
  async deleteTokensByEmail(email: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('reset_tokens')
        .delete()
        .eq('email', email);

      if (error) throw error;
      return true;
    } catch (error) {
      return false;
    }
  }
}

// Database operations for challenges
export class ChallengeDB {
  private static instance: ChallengeDB;

  static getInstance(): ChallengeDB {
    if (!ChallengeDB.instance) {
      ChallengeDB.instance = new ChallengeDB();
    }
    return ChallengeDB.instance;
  }

  // Create a new challenge
  async createChallenge(challengerId: string, opponentId: string, durationSeconds: number = 600): Promise<Challenge | null> {
    try {
      const { data, error } = await supabase
        .from('challenges')
        .insert({
          challenger_id: challengerId,
          opponent_id: opponentId,
          status: 'active',
          started_at: new Date().toISOString(),
          duration_seconds: durationSeconds
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error creating challenge:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get challenge by ID
  async getChallengeById(challengeId: string): Promise<Challenge | null> {
    try {
      const { data, error } = await supabase
        .from('challenges')
        .select('*')
        .eq('id', challengeId)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Get active challenges for a user
  async getActiveChallengesForUser(userId: string): Promise<Challenge[]> {
    try {
      const { data, error } = await supabase
        .from('challenges')
        .select('*')
        .or(`challenger_id.eq.${userId},opponent_id.eq.${userId}`)
        .eq('status', 'active')
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    } catch (error) {
      return [];
    }
  }

  // Update challenge status
  async updateChallengeStatus(challengeId: string, status: 'pending' | 'active' | 'completed' | 'cancelled', winnerId?: string): Promise<Challenge | null> {
    try {
      const updateData: any = { status };
      
      if (status === 'completed') {
        updateData.ended_at = new Date().toISOString();
      }
      
      if (winnerId) {
        updateData.winner_id = winnerId;
      }

      const { data, error } = await supabase
        .from('challenges')
        .update(updateData)
        .eq('id', challengeId)
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Subscribe to challenge changes
  subscribeToChallenge(challengeId: string, callback: (payload: any) => void) {
    try {
      const subscription = supabase
        .channel(`challenge_${challengeId}`)
        .on('postgres_changes',
          { event: '*', schema: 'public', table: 'challenges', filter: `id=eq.${challengeId}` },
          callback
        )
        .subscribe();

      return subscription;
    } catch (error: any) {
      console.error('Error subscribing to challenge:', error?.message || error, error?.details, error?.hint, error?.code);
    }
  }

  // Unsubscribe from challenge
  unsubscribeFromChallenge(challengeId: string) {
    try {
      supabase.channel(`challenge_${challengeId}`).unsubscribe();
    } catch (error: any) {
      console.error('Error unsubscribing from challenge:', error?.message || error, error?.details, error?.hint, error?.code);
    }
  }
}

// Database operations for challenge sessions
export class ChallengeSessionDB {
  private static instance: ChallengeSessionDB;

  static getInstance(): ChallengeSessionDB {
    if (!ChallengeSessionDB.instance) {
      ChallengeSessionDB.instance = new ChallengeSessionDB();
    }
    return ChallengeSessionDB.instance;
  }

  // Create a new challenge session
  async createSession(challengeId: string, userId: string): Promise<ChallengeSession | null> {
    try {
      const { data, error } = await supabase
        .from('challenge_sessions')
        .insert({
          challenge_id: challengeId,
          user_id: userId,
          study_time_seconds: 0,
          is_studying: true,
          session_start_time: new Date().toISOString()
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error creating challenge session:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get sessions for a challenge
  async getSessionsForChallenge(challengeId: string): Promise<ChallengeSession[]> {
    try {
      const { data, error } = await supabase
        .from('challenge_sessions')
        .select('*')
        .eq('challenge_id', challengeId);

      if (error) throw error;
      return data || [];
    } catch (error) {
      return [];
    }
  }

  // Get session for a user in a challenge
  async getSessionForUser(challengeId: string, userId: string): Promise<ChallengeSession | null> {
    try {
      const { data, error } = await supabase
        .from('challenge_sessions')
        .select('*')
        .eq('challenge_id', challengeId)
        .eq('user_id', userId)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Update session study time and status
  async updateSession(sessionId: string, studyTimeSeconds: number, isStudying: boolean): Promise<ChallengeSession | null> {
    try {
      const { data, error } = await supabase
        .from('challenge_sessions')
        .update({
          study_time_seconds: studyTimeSeconds,
          is_studying: isStudying
        })
        .eq('id', sessionId)
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Subscribe to session changes for a challenge
  subscribeToChallengeSessions(challengeId: string, callback: (payload: any) => void) {
    try {
      const subscription = supabase
        .channel(`challenge_sessions_${challengeId}`)
        .on('postgres_changes',
          { event: '*', schema: 'public', table: 'challenge_sessions', filter: `challenge_id=eq.${challengeId}` },
          callback
        )
        .subscribe();

      return subscription;
    } catch (error: any) {
      console.error('Error subscribing to challenge sessions:', error?.message || error, error?.details, error?.hint, error?.code);
    }
  }

  // Unsubscribe from challenge sessions
  unsubscribeFromChallengeSessions(challengeId: string) {
    try {
      supabase.channel(`challenge_sessions_${challengeId}`).unsubscribe();
    } catch (error: any) {
      console.error('Error unsubscribing from challenge sessions:', error?.message || error, error?.details, error?.hint, error?.code);
    }
  }
}

// Database operations for waiting list
export class WaitingListDB {
  private static instance: WaitingListDB;

  static getInstance(): WaitingListDB {
    if (!WaitingListDB.instance) {
      WaitingListDB.instance = new WaitingListDB();
    }
    return WaitingListDB.instance;
  }

  // Add user to waiting list
  async addToWaitingList(userId: string): Promise<WaitingListEntry | null> {
    try {
      // First, delete any existing waiting entry for this user (expired or not)
      await supabase
        .from('challenge_waiting_list')
        .delete()
        .eq('user_id', userId)
        .eq('status', 'waiting');

      // Then add new entry
      const { data, error } = await supabase
        .from('challenge_waiting_list')
        .insert({
          user_id: userId,
          status: 'waiting',
          expires_at: new Date(Date.now() + 5 * 60 * 1000).toISOString() // 5 minutes
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error adding to waiting list:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Remove user from waiting list
  async removeFromWaitingList(userId: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('challenge_waiting_list')
        .update({ status: 'matched' })
        .eq('user_id', userId)
        .eq('status', 'waiting');

      if (error) throw error;
      return true;
    } catch (error: any) {
      console.error('Error removing from waiting list:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Find a match in waiting list
  async findMatch(userId: string): Promise<WaitingListEntry | null> {
    try {
      console.log('Finding match for user:', userId);
      // Cleanup expired entries first
      await supabase
        .from('challenge_waiting_list')
        .delete()
        .eq('status', 'waiting')
        .lt('expires_at', new Date().toISOString());

      // Find a waiting user
      const { data, error } = await supabase
        .from('challenge_waiting_list')
        .select('*')
        .eq('status', 'waiting')
        .neq('user_id', userId)
        .gt('expires_at', new Date().toISOString())
        .order('joined_at', { ascending: true })
        .limit(1)
        .maybeSingle();

      console.log('Match query result:', data, 'Error:', error);
      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error finding match:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get user's current waiting entry
  async getUserWaitingEntry(userId: string): Promise<WaitingListEntry | null> {
    try {
      const { data, error } = await supabase
        .from('challenge_waiting_list')
        .select('*')
        .eq('user_id', userId)
        .eq('status', 'waiting')
        .gt('expires_at', new Date().toISOString())
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error) {
      return null;
    }
  }

  // Subscribe to waiting list changes
  subscribeToWaitingList(callback: (payload: any) => void) {
    try {
      const subscription = supabase
        .channel('waiting_list_changes')
        .on('postgres_changes',
          { event: '*', schema: 'public', table: 'challenge_waiting_list' },
          callback
        )
        .subscribe();

      return subscription;
    } catch (error: any) {
      console.error('Error subscribing to waiting list:', error?.message || error, error?.details, error?.hint, error?.code);
    }
  }

  // Unsubscribe from waiting list
  unsubscribeFromWaitingList() {
    try {
      supabase.channel('waiting_list_changes').unsubscribe();
    } catch (error: any) {
      console.error('Error unsubscribing from waiting list:', error?.message || error, error?.details, error?.hint, error?.code);
    }
  }
}

// Database operations for referrals
export class ReferralDB {
  private static instance: ReferralDB;

  static getInstance(): ReferralDB {
    if (!ReferralDB.instance) {
      ReferralDB.instance = new ReferralDB();
    }
    return ReferralDB.instance;
  }

  // Generate a unique referral code
  generateReferralCode(): string {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 8; i++) {
      code += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return code;
  }

  // Create a new referral
  async createReferral(referrerId: string, referredUserId: string, referralCode: string): Promise<Referral | null> {
    try {
      const { data, error } = await supabase
        .from('referrals')
        .insert({
          referrer_id: referrerId,
          referred_user_id: referredUserId,
          referral_code: referralCode,
          points_rewarded: 40
        })
        .select()
        .single();

      if (error) {
        console.error('Supabase error:', error.message, error.details, error.hint, error.code);
        throw error;
      }
      return data;
    } catch (error: any) {
      console.error('Error creating referral:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get referral by code
  async getReferralByCode(referralCode: string): Promise<Referral | null> {
    try {
      const { data, error } = await supabase
        .from('referrals')
        .select('*')
        .eq('referral_code', referralCode)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error getting referral by code:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get all referrals for a referrer
  async getReferralsByReferrer(referrerId: string): Promise<Referral[]> {
    try {
      const { data, error } = await supabase
        .from('referrals')
        .select('*')
        .eq('referrer_id', referrerId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    } catch (error: any) {
      console.error('Error getting referrals by referrer:', error?.message || error, error?.details, error?.hint, error?.code);
      return [];
    }
  }

  // Check if a user has already been referred
  async hasUserBeenReferred(userId: string): Promise<boolean> {
    try {
      const { data, error } = await supabase
        .from('referrals')
        .select('id')
        .eq('referred_user_id', userId)
        .maybeSingle();

      if (error) throw error;
      return data !== null;
    } catch (error: any) {
      console.error('Error checking if user has been referred:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Get total points earned from referrals
  async getTotalReferralPoints(referrerId: string): Promise<number> {
    try {
      const { data, error } = await supabase
        .from('referrals')
        .select('points_rewarded')
        .eq('referrer_id', referrerId);

      if (error) throw error;

      const totalPoints = data?.reduce((sum, referral) => sum + referral.points_rewarded, 0) || 0;
      return totalPoints;
    } catch (error: any) {
      console.error('Error getting total referral points:', error?.message || error, error?.details, error?.hint, error?.code);
      return 0;
    }
  }

  // Get user by referral code
  async getUserByReferralCode(referralCode: string): Promise<UserAccount | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('*')
        .eq('referral_code', referralCode)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error getting user by referral code:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }
}

// Database operations for study rooms
export class RoomDB {
  private static instance: RoomDB;

  static getInstance(): RoomDB {
    if (!RoomDB.instance) {
      RoomDB.instance = new RoomDB();
    }
    return RoomDB.instance;
  }

  // Create a new study room
  async createRoom(name: string, creatorId: string): Promise<StudyRoom | null> {
    try {
      const { data, error } = await supabase
        .from('study_rooms')
        .insert({
          name,
          creator_id: creatorId
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error creating room:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get all rooms
  async getAllRooms(): Promise<StudyRoom[]> {
    try {
      const { data, error } = await supabase
        .from('study_rooms')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    } catch (error: any) {
      console.error('Error getting rooms:', error?.message || error, error?.details, error?.hint, error?.code);
      return [];
    }
  }

  // Get room by ID
  async getRoomById(roomId: string): Promise<StudyRoom | null> {
    try {
      const { data, error } = await supabase
        .from('study_rooms')
        .select('*')
        .eq('id', roomId)
        .single();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error getting room:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Delete a room
  async deleteRoom(roomId: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('study_rooms')
        .delete()
        .eq('id', roomId);

      if (error) throw error;
      return true;
    } catch (error: any) {
      console.error('Error deleting room:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Join a room
  async joinRoom(roomId: string, userId: string): Promise<RoomMember | null> {
    try {
      // Use upsert to handle both new joins and rejoins in a single operation
      // If the record exists (user was in room before), update left_at to null
      // If it doesn't exist, insert a new record
      const { data, error } = await supabase
        .from('room_members')
        .upsert({
          room_id: roomId,
          user_id: userId,
          left_at: null, // Always set to null on join/rejoin
          last_heartbeat: new Date().toISOString()
        }, {
          onConflict: 'room_id,user_id',
          ignoreDuplicates: false
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error joining room:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Get all members in a room
  async getRoomMembers(roomId: string): Promise<RoomMember[]> {
    try {
      const { data, error } = await supabase
        .from('room_members')
        .select('*')
        .eq('room_id', roomId)
        .is('left_at', null)
        .order('joined_at', { ascending: false });

      if (error) throw error;
      return data || [];
    } catch (error: any) {
      console.error('Error getting room members:', error?.message || error, error?.details, error?.hint, error?.code);
      return [];
    }
  }

  // Update heartbeat for a member
  async updateHeartbeat(roomId: string, userId: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('room_members')
        .update({ last_heartbeat: new Date().toISOString() })
        .eq('room_id', roomId)
        .eq('user_id', userId)
        .is('left_at', null);

      if (error) throw error;
      return true;
    } catch (error: any) {
      console.error('Error updating heartbeat:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Leave a room
  async leaveRoom(roomId: string, userId: string): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('room_members')
        .update({ left_at: new Date().toISOString() })
        .eq('room_id', roomId)
        .eq('user_id', userId)
        .is('left_at', null);

      if (error) throw error;
      return true;
    } catch (error: any) {
      console.error('Error leaving room:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Get user's current room (if any)
  async getUserCurrentRoom(userId: string): Promise<RoomMember | null> {
    try {
      const { data, error } = await supabase
        .from('room_members')
        .select('*')
        .eq('user_id', userId)
        .is('left_at', null)
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error getting user current room:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Clean up inactive members (no heartbeat for 2 minutes)
  async cleanupInactiveMembers(): Promise<boolean> {
    try {
      const twoMinutesAgo = new Date(Date.now() - 2 * 60 * 1000).toISOString();
      
      const { error } = await supabase
        .from('room_members')
        .delete()
        .lt('last_heartbeat', twoMinutesAgo);

      if (error) throw error;
      return true;
    } catch (error: any) {
      console.error('Error cleaning up inactive members:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Get users by their IDs
  async getUsersByIds(userIds: string[]): Promise<UserAccount[]> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('id, account_id, username, email, avatar, score, last_active, created_at, hash_key')
        .in('id', userIds);

      if (error) throw error;
      return data || [];
    } catch (error: any) {
      console.error('Error getting users by IDs:', error?.message || error, error?.details, error?.hint, error?.code);
      return [];
    }
  }
}

// Discord OTP interface for database (snake_case - matches Supabase)
export interface DiscordOTP {
  id?: string;
  user_hash_key: string;
  otp_code: string;
  expires_at: string;
  used: boolean;
  created_at: string;
}

// Discord OTP interface for frontend (camelCase)
export interface DiscordOTPFrontend {
  id?: string;
  userHashKey: string;
  otpCode: string;
  expiresAt: string;
  used: boolean;
  createdAt: string;
}

// Discord OTP Database Operations
class DiscordOTPDB {
  private static instance: DiscordOTPDB;

  private constructor() {}

  static getInstance(): DiscordOTPDB {
    if (!DiscordOTPDB.instance) {
      DiscordOTPDB.instance = new DiscordOTPDB();
    }
    return DiscordOTPDB.instance;
  }

  // Generate and store OTP for a user
  async generateOTP(userHashKey: string): Promise<string | null> {
    try {
      // Generate 6-digit OTP
      const seed = userHashKey + Date.now();
      const otp = Math.floor(Math.abs(parseInt(seed.slice(0, 10), 36))) % 1000000;
      const otpString = otp.toString().padStart(6, '0');

      // Calculate expiry time (5 minutes from now)
      const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString();

      // Use upsert to insert or replace existing OTP
      const { error } = await supabase
        .from('discord_otps')
        .upsert({
          user_hash_key: userHashKey,
          otp_code: otpString,
          expires_at: expiresAt,
          used: false
        }, {
          onConflict: 'user_hash_key'
        });

      if (error) throw error;

      return otpString;
    } catch (error: any) {
      console.error('Error generating Discord OTP:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Verify OTP code for a user
  async verifyOTP(userHashKey: string, otpCode: string): Promise<boolean> {
    try {
      const { data, error } = await supabase
        .from('discord_otps')
        .select('*')
        .eq('user_hash_key', userHashKey)
        .eq('otp_code', otpCode)
        .eq('used', false)
        .gt('expires_at', new Date().toISOString())
        .maybeSingle();

      if (error) throw error;

      if (!data) {
        return false; // Invalid or expired OTP
      }

      // Mark OTP as used
      await supabase
        .from('discord_otps')
        .update({ used: true })
        .eq('id', data.id);

      return true;
    } catch (error: any) {
      console.error('Error verifying Discord OTP:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }

  // Get OTP for a user (for display purposes)
  async getOTP(userHashKey: string): Promise<DiscordOTP | null> {
    try {
      const { data, error } = await supabase
        .from('discord_otps')
        .select('*')
        .eq('user_hash_key', userHashKey)
        .eq('used', false)
        .gt('expires_at', new Date().toISOString())
        .maybeSingle();

      if (error) throw error;
      return data;
    } catch (error: any) {
      console.error('Error getting Discord OTP:', error?.message || error, error?.details, error?.hint, error?.code);
      return null;
    }
  }

  // Clean up expired OTPs
  async cleanupExpired(): Promise<boolean> {
    try {
      const { error } = await supabase
        .from('discord_otps')
        .delete()
        .lt('expires_at', new Date().toISOString());

      if (error) throw error;
      return true;
    } catch (error: any) {
      console.error('Error cleaning up expired Discord OTPs:', error?.message || error, error?.details, error?.hint, error?.code);
      return false;
    }
  }
}

// Export singleton instances
export const userDB = UserAccountDB.getInstance();
export const resetTokenDB = ResetTokenDB.getInstance();
export const challengeDB = ChallengeDB.getInstance();
export const challengeSessionDB = ChallengeSessionDB.getInstance();
export const waitingListDB = WaitingListDB.getInstance();
export const referralDB = ReferralDB.getInstance();
export const roomDB = RoomDB.getInstance();
export const discordOTPDB = DiscordOTPDB.getInstance();

// Check if Supabase is available
export const isSupabaseAvailable = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.from('users').select('account_id').limit(1);
    
    if (error) {
      return false;
    }
    
    return true;
  } catch (error) {
    return false;
  }
};
